### ISSUE TITLE
Test Todo controller endpoints

### ISSUE THREAD

**Issue by auxcoder** [auxcoder/express-basic-api#21]
- [x] get/todos
- [x] get/todo/id
- [x] del/todo/id
- [x] patch/todo/id
- [x] post/todo/id
